baseURL = "https://webrtcforthecurious.com"
theme = "book"

# Enable 'Last Modified by' date and git author information
enableGitInfo = true

DefaultContentLanguage = "en"
[languages]
  [languages.en]
    title = "WebRTC for the Curious"
    languageName = "English"
    weight = 1
  [languages.tr]
    title = "WebRTC for the Curious -- TODO Translate to Turkish"
    languageName = "Turkish"
    contentDir = "content.tr"
    weight = 2
  [languages.fa]
    title = "WebRTC برای کنجکاوها"
    languageName = "Persian"
    languagedirection = "rtl"
    contentDir = "content.fa"
    weight = 3
  [languages.zh]
    title = "给好奇者的WebRTC"
    languageName = "简体中文"
    contentDir = "content.zh-cn"
    weight = 4

[params]
  # source repository location.
  # Used for 'Last Modified' and 'Edit this page' links.
  BookRepo = 'https://github.com/webrtc-for-the-curious/webrtc-for-the-curious'

  # 'Edit this page' links
  BookEditPath = 'edit/master/content'
